let fruits: string[] = [
  "Apple",
  "Orange",
  "Banana",
  "Mango",
  "Grapes",
  "Watermelon",
  "Strawberry",
  "Kiwi",
  "Pineapple",
  "Blueberry",
  "Peach",
  "Pear",
  "Cherry",
  "Raspberry",
  "Blackberry",
  "Cantaloupe",
  "Honeydew",
  "Lemon",
  "Lime",
  "Coconut",
  "Pomegranate",
  "Avocado",
  "Fig",
  "Guava",
  "Apricot",
  "Passion Fruit",
  "Plum",
  "Papaya",
  "Cranberry",
  "Rambutan",
  "Dragon Fruit",
  "Kiwi",
  "Lychee",
  "Nectarine",
  "Grapefruit",
  "Kiwi",
  "Clementine",
  "Cactus Fruit",
  "Persimmon",
  "Star Fruit",
  "Mandarin Orange",
  "Mulberry",
  "Elderberry",
  "Gooseberry",
  "Currant",
  "Jackfruit",
  "Date",
  "Quince",
  "Kumquat",
  "Tangerine",
  "Cranberry",
  "Raspberry",
  "Boysenberry",
  "Loganberry",
  "Goji Berry",
  "Kiwi Berry",
  "Mango",
  "Apricot",
  "Papaya",
  "Cherry Tomato",
  "Cucumber",
  "Zucchini",
  "Pumpkin",
  "Squash",
  "Bell Pepper",
  "Tomato",
  "Eggplant",
  "Watermelon",
  "Cantaloupe",
  "Honeydew",
  "Passion Fruit",
  "Pomegranate",
  "Fig",
  "Avocado",
  "Persimmon",
  "Dragon Fruit",
  "Star Fruit",
  "Pineapple",
  "Coconut",
  "Lychee",
  "Banana",
  "Plantain",
  "Guava",
  "Papaya",
  "Passion Fruit",
  "Mango",
  "Pineapple",
  "Kiwi",
  "Watermelon",
];

// Display the array of 100 fruits
for (let index = 0; index < fruits.length; index++) {
  const element = fruits[index];
  console.log(`${index + 1} fruit: ${element}`);
}
