"use strict";
let a = 16;
let b = 8;
let sum = a + b;
let subs = a - b;
let div = a / b;
let mult = a * b;
console.log("Sum :", sum);
console.log("Substraction :", subs);
console.log("Division :", div);
console.log("Multliplication :", mult);
